### PR TITLE
add a perturbation response example

### PR DESCRIPTION
**Pull request by yairchn**
# Earth-2 MIP Pull Request

## Description
This MR adds the `model` a nudge property that attributes to a function, specified in `inference_ensemble.py`. This prescribed nudging is applied between steps, with units of var/day, where var could be dimensional or non dimensional depending on the model. A notebook for preforming a perturbation response experiment in earth2mip is added. 

Closes: https://github.com/NVIDIA/earth2mip/issues/41

## Checklist

- [x] I am familiar with the Contributing Guidelines.
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [X] The CHANGELOG.md is up to date with these changes.
- [X] An [issue](https://github.com/NVIDIA/earth2mip/issues) is linked to this pull request.

### CODE REVIEW

**Comment by yairchn** [comment]
@NickGeneva thanks for the help the changes work with `fcnv2_sm` but not with `pangu`

if you run the notebook you get:
```
INFO:inference:ensemble members 1-1/1
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/earth2mip/inference_ensemble.py", line 421, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/earth2mip/inference_ensemble.py", line 229, in main
    run_inference(model, config, perturb, group)
  File "/usr/local/lib/python3.10/dist-packages/earth2mip/inference_ensemble.py", line 395, in run_inference
    run_ensembles(
  File "/usr/local/lib/python3.10/dist-packages/earth2mip/inference_ensemble.py", line 135, in run_ensembles
    iterator = model(time, x, normalize=False)
TypeError: PanguInference.__call__() got an unexpected keyword argument 'normalize'
```

**Comment by nbren12** [comment]
Let's hold off no merging this until I return next week.

We should not be adding new methods/properties to earth2mip.networks.Inference. see #14.

**Comment by nbren12** [comment]
Also, the notebook needs to be removed. It has outputs and experimental stuff should not go here.

**Comment by nbren12** [comment]
I propose these changes since the config handling is not straightforward.

- combine #42 and #33.
- rename “noise_injection” to something more general perhaps just “perturb”.
- delete any config handling/construction logic
- make two examples in examples/workflows/ as an alternative to the config stuff.
- Add tests for the noise injection feature of networks.Inference and pangu.PanguWeather

**Pull request merged**
